type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "1990":[
    {title: "同级生2"},
    {title: "心跳回忆"},
    {title: "樱花大战"},
    {title: "鬼畜王兰斯"},
    {title: "Kanon"},
    {title: "加奈妹妹"},
    {title: "秋之回忆"},
    {title: "白色相簿"},
    {title: "雫"},
    {title: "在世界尽头咏唱恋曲的少女YU-NO"},
    {title: "ONE"},
    {title: "遗作"},
  ],
  "2000":[
    {title: "幻灵镇魂曲"},
    {title: "Never7"},
    {title: "银色"},
    {title: "AIR"},
    {title: "月姬"},
    {title: "对你说再见"},
    {title: "鬼作"},
    {title: "幻燐的姬将军"},
    {title: "秋之回忆2"},
    {title: "自杀的101种方法"},
    {title: "家族计画"},
    {title: "大恶司"},
  ],
  "2002":[
    {title: "腐姫"},
    {title: "鬼哭街"},
    {title: "传颂之物"},
    {title: "初音岛"},
    {title: "超昂天使"},
    {title: "寒蝉鸣泣之时"},
    {title: "战女神2"},
    {title: "BALDR FORCE"},
    {title: "樱花大战4"},
    {title: "水月"},
    {title: "白诘草话"},
    {title: "皋月物语"},
  ],
  "2003":[
    {title: "SNOW"},
    {title: "Cannonball～猫猫疯狂大赛车～"},
    {title: "Muv-Luv"},
    {title: "没有天使的12月"},
    {title: "女仆咖啡巧克拉"},
    {title: "斩魔大圣Demonbane"},
    {title: "时空轮回"},
    {title: "永远的艾塞莉娅"},
    {title: "沙耶之歌"},
    {title: "夏梦夜话"},
    {title: "CROSS†CHANNEL"},
    {title: "夜月东升•暮日西沉"},
  ],
  "2004":[
    {title: "Remember11"},
    {title: "交响乐之雨"},
    {title: "CLANNAD"},
    {title: "CARNIVAL"},
    {title: "Fate/stay night"},
    {title: "秋之回忆：从今以后"},
    {title: "3days ～在逝去时间的另一端～"},
    {title: "巢作之龙"},
    {title: "春天的足音"},
    {title: "兰斯6 - 赛斯崩坏 -"},
    {title: "神树之馆"},
    {title: "星之梦"},
  ],
  "2005":[
    {title: "少女爱上姐姐"},
    {title: "120元之春"},
    {title: "女仆咖啡帕露菲"},
    {title: "恋狱～月狂病～"},
    {title: "日在校园"},
    {title: "妖人"},
    {title: "天鹅之歌"},
    {title: "水仙"},
    {title: "梦见之药"},
    {title: "娇蛮之吻"},
    {title: "更胜黎明前的琉璃色"},
    {title: "车轮之国，向日葵的少女"},
  ],
  "2006": [
    { title: "Muv-Luv Alternative", score: 8.4 },
    { title: "假如明日天放晴", score: 8.7 },
    { title: "青空下的约定", score: 8 },
    { title: "望见青空之丘", score: 8.3 },
    { title: "初音岛2", score: 8.2 },
    { title: "日常与非日常的境界线", score: 7.1 },
    { title: "妻管严", score: 8.2 },
    { title: "虫爱少女", score: 7 },
    { title: "遥仰凰华", score: 7.8 },
    { title: "战国兰斯", score: 7.7 },
    { title: "ef - the first tale.", score: 8 },
    { title: "H2O -FOOTPRINTS IN THE SAND-", score: 7.5 },
  ],
  "2007": [
    { title: "恋姬无双", score: 8.3 },
    { title: "终有一日愿遂彼空", score: 8.3 },
    { title: "月光嘉年华", score: 8.6 },
    { title: "KIRA☆KIRA 煌煌舞台", score: 7.4 },
    { title: "王贼", score: 7.6 },
    { title: "染成茜色的坂道", score: 7.9 },
    { title: "Little Busters!", score: 7.9 },
    { title: "续·杀戮之姜戈", score: 8.2 },
    { title: "海猫鸣泣之时", score: 7.6 },
    { title: "明日的世界", score: 7.8 },
    { title: "世界上最NG的恋爱", score: 6.3 },
    { title: "Aster", score: 7.6 },
  ],
  "2008": [
    { title: "赤色约定", score: 6.9 },
    { title: "媚肉之香", score: 8 },
    { title: "晓之护卫", score: 6.8 },
    { title: "11eyes-罪与罚与救赎之少女-", score: 7.8 },
    { title: "CHAOS;HEAD", score: 8 },
    { title: "夏空彼方", score: 7.5 },
    { title: "G弦上的魔王", score: 7.1 },
    { title: "ef - the latter tale.", score: 6.1 },
    { title: "战女神ZERO", score: 7.4 },
    { title: "智以泪聚", score: 7 },
    { title: "壳之少女", score: 7.8 },
    { title: "缘之空", score: 6.2 },
  ],
  "2009": [
    { title: "我们没有翅膀", score: 8.2 },
    { title: "星空的记忆 -流星下的愿景-", score: 8.8 },
    { title: "BALDR SKY Dive1+2", score: 8.4 },
    { title: "从晴朗的朝色泛起之际开始", score: 8 },
    { title: "夏梦渚", score: 7.5 },
    { title: "eden*", score: 7.4 },
    { title: "夏之雨", score: 7.3 },
    { title: "STEINS;GATE", score: 7.5 },
    { title: "装甲恶鬼村正", score: 7.3 },
    { title: "纯白交响曲", score: 7.4 },
    { title: "死神之吻乃离别之味", score: 7.6 },
    { title: "认真和我谈恋爱", score: 7.6 },
  ],
  "2010": [
    { title: "美好的每一天～不连续的存在～", score: 8 },
    { title: "WHITE ALBUM2 ～introductory chapter～", score: 8.6 },
    { title: "恋色空模样", score: 7.5 },
    { title: "实妹相伴的大泉君", score: 6.6 },
    { title: "黄昏的禁忌之药", score: 7.4 },
    { title: "架向星空之桥", score: 7.5 },
    { title: "恋爱与选举与巧克力", score: 7.9 },
    { title: "Noble☆Works", score: 7.2 },
    { title: "逆转爱恋", score: 7.3 },
    { title: "君之余影静静地摇曳着", score: 7.1 },
    { title: "如月 金★星", score: 7.8 },
    { title: "紫影的索纳尼尔～何等美好的记忆～", score: 6.7 },
  ],
  "2011": [
    { title: "灰色的果实", score: 8.8 },
    { title: "秽翼的尤斯蒂娅", score: 8.5 },
    { title: "民工女友", score: 8.1 },
    { title: "euphoria", score: 8.6 },
    { title: "Rewrite", score: 8 },
    { title: "隙间樱花与谎言都市", score: 7.6 },
    { title: "五彩斑斓的世界", score: 7.6 },
    { title: "不要践踏天使的羽毛", score: 6.5 },
    { title: "未来乡愁", score: 7.5 },
    { title: "妹调教日记", score: 8.3 },
    { title: "WHITE ALBUM2 ～closing chapter～", score: 7.3 },
    { title: "无限炼奸", score: 6.8 },
  ],
  "2012": [
    { title: "灰色的迷宫", score: 8.2 },
    { title: "初雪樱", score: 7.8 },
    { title: "魔法使之夜", score: 7.9 },
    { title: "海市蜃楼之馆", score: 7.4 },
    { title: "在这苍穹展翅", score: 8.2 },
    { title: "Root Double", score: 7.8 },
    { title: "世界终结与生日快乐", score: 7 },
    { title: "时钟机关的Ley-line -黄昏时的境界线-", score: 7.4 },
    { title: "古色迷宫轮舞曲", score: 7.9 },
    { title: "魔女的花园", score: 6.9 },
    { title: "夏空的英仙座", score: 7.3 },
    { title: "近月少女的礼仪", score: 7.9 },
  ],
  "2013": [
    { title: "大图书馆的牧羊人", score: 8.2 },
    { title: "虚之少女", score: 8.1 },
    { title: "向日葵教会和长长的暑假", score: 7.5 },
    { title: "灰色的乐园", score: 8 },
    { title: "忠臣蔵46+1", score: 7.2 },
    { title: "你和她和她的恋爱。", score: 7.1 },
    { title: "Friend to Lover", score: 6.6 },
    { title: "少女理论及其周边 -Ecole de Paris-", score: 6.6 },
    { title: "BAPLDR SKY ZERO", score: 7.5 },
    { title: "幸福噩梦", score: 6.9 },
    { title: "魔导巧壳", score: 6.9 },
    { title: "天色幻想岛", score: 6.8 },
  ],
  "2014": [
    { title: "幸运草的约定", score: 8.7 },
    { title: "航迹云的彼方", score: 8 },
    { title: "CHAOS;CHILD", score: 7.5 },
    { title: "兰斯9 赫尔曼革命", score: 7.7 },
    { title: "魔女恋爱日记", score: 8.7 },
    { title: "友爱俱乐部", score: 7 },
    { title: "星辰恋曲的白色永恒", score: 8 },
    { title: "雨恋", score: 7.1 },
    { title: "若能与你再次相见", score: 7.8 },
    { title: "纸上魔法使", score: 7.3 },
    { title: "晴霁之后定是菜花盛开的好天气", score: 6.6 },
    { title: "苍之彼方的四重奏", score: 8 },
  ],
  "2015": [
    { title: "永不落幕的前奏诗", score: 7.2 },
    { title: "魔女的夜宴", score: 7.3 },
    { title: "五色浮影绽放于花之海洋", score: 8 },
    { title: "夏娃年代记", score: 5.8 },
    { title: "与你心相连", score: 6.3 },
    { title: "传颂之物 虚伪的假面", score: 6.9 },
    { title: "樱之诗", score: 7.3 },
    { title: "喜欢我的话就要说出来！", score: 7 },
    { title: "想要传达给你的爱恋", score: 6.8 },
    { title: "SeaBed", score: 6.8 },
    { title: "命运石之门 0", score: 8.3 },
    { title: "仰望夜空的星辰", score: 7.8 },
  ],
  "2016": [
    { title: "千之刃涛，桃花染之皇姬", score: 7.6 },
    { title: "任性High Spec", score: 8.3 },
    { title: "ISLAND", score: 7.7 },
    { title: "野良与皇女与流浪猫之心", score: 7.7 },
    { title: "罪之光约会", score: 7.4 },
    { title: "神怒之日 ～夜访穿刺公～", score: 7.7 },
    { title: "爱上火车", score: 7.8 },
    { title: "少女＊领域", score: 7.5 },
    { title: "濒死轮回的卿于馆中萌生的憎恶", score: 7.3 },
    { title: "天津罪", score: 7.5 },
    { title: "千恋＊万花", score: 7.5 },
    { title: "生命的备件", score: 7.4 },
  ],
  "2017": [
    { title: "月影魅像-解放之羽-", score: 8.1 },
    { title: "糖调! -sugarfull tempering-", score: 8.2 },
    { title: "水葬银币的Istria", score: 7.4 },
    { title: "新妻LOVELY×CATION", score: 7 },
    { title: "9-nine-九次九日九重色", score: 7.6 },
    { title: "牛顿与苹果树", score: 7.9 },
    { title: "流景之海的艾佩理雅", score: 7.9 },
    { title: "青鸟", score: 6.4 },
    { title: "牵绊闪耀的恋之伊吕波", score: 7.2 },
    { title: "突然＊恋人", score: 7.7 },
    { title: "夜晚徘徊在我们的辅导教室", score: 7.3 },
    { title: "金辉恋曲四重奏", score: 6.6 },
  ],
  "2018": [
    { title: "兰斯10 决战", score: 8.2 },
    { title: "9-nine-天色天歌天籁音", score: 7.8 },
    { title: "Summer Pockets", score: 7 },
    { title: "住在拔作岛上的贫乳应该如何是好？", score: 7.5 },
    { title: "未来广播与人工鸽", score: 8.3 },
    { title: "5分钟的邂逅！时间停止与不可避免的命运！", score: 7.9 },
    { title: "奇异恩典·圣夜的小镇", score: 7.5 },
    { title: "RIDDLE JOKER", score: 7.8 },
    { title: "乌有乡", score: 8.2 },
    { title: "丑小鸭与文字祸", score: 7.4 },
    { title: "寄宿之恋", score: 6.7 },
    { title: "宿星的女朋友 -destiny star girlfriend-", score: 7.8 },
  ],
  "2019": [
    { title: "樱花萌放-as the Night's, Reincarnation-", score: 8.3 },
    { title: "青夏轨迹", score: 7.8 },
    { title: "青空下的加缪", score: 7.5 },
    { title: "pieces/候鸟的梦", score: 7.3 },
    { title: "9-nine-春色春恋春熙风", score: 6.5 },
    { title: "玉响未来", score: 7.6 },
    { title: "初音岛4", score: 6.9 },
    { title: "相逢在明月映照的彼岸", score: 7.3 },
    { title: "星光咖啡馆与死神之蝶", score: 7.3 },
    { title: "住在拔作岛上的贫乳应该如何是好？2", score: 6.5 },
    { title: "异想魅惑", score: 6 },
    { title: "你喜欢的是哪个我呢?", score: 7.6 },
  ],
  "2020": [
    { title: "红月摇曳的恋之星火", score: 7.7 },
    { title: "丸子与银河龙", score: 7.1 },
    { title: "献给神明般的你", score: 7.3 },
    { title: "星空列车与白的旅行", score: 7.5 },
    { title: "9-nine-雪色雪花雪之痕", score: 8.1 },
    { title: "美少女万华镜 -理与迷宫的少女-", score: 7.1 },
    { title: "亚托莉 -我挚爱的时光-", score: 6.3 },
    { title: "天之少女", score: 7.7 },
    { title: "樱色之云＊绯色之恋", score: 6.3 },
    { title: "白日梦的构想图", score: 6.9 },
    { title: "常轨脱离Creative", score: 5.5 },
    { title: "爱因斯坦携爱敬上’", score: 7.3 },
  ],
  "2021": [
    { title: "冥契的牧神节", score: 7.6 },
    { title: "魔法少女消耗战线 死终Ω神盾", score: 7.9 },
    { title: "日向千寻的工作总是做不久", score: 6.2 },
    { title: "雪色暗号", score: 8.5 },
    { title: "巧克甜恋2", score: 6.3 },
    { title: "雪境迷途遇仙踪", score: 7.8 },
    { title: "月姬 -A piece of blue glass moon-", score: 6.8 },
    { title: "冬暮，川滚滚。", score: 6.3 },
    { title: "Monkeys!¡", score: 7 },
    { title: "创作少女的恋爱方程式", score: 6.8 },
    { title: "我们是不能延期了", score: 6.4 },
    { title: "久那土国记", score: 6.8 },
  ],
  "2022": [
    { title: "变态监狱", score: 8.4 },
    { title: "废村少女~诱惑迷离的笼之乡~", score: 6.3 },
    { title: "Unless Terminalia", score: 7.1 },
    { title: "恋爱成双", score: 7.5 },
    { title: "AMBITIOUS MISSION", score: 7.6 },
    { title: "无法忍耐的处男哥哥和不直率的叛逆妹妹", score: 7.2 },
    { title: "霞流宝石心 -壮志凌云振寰宇-", score: 7.4 },
    { title: "传述之魔女", score: 6.4 },
    { title: "甜蜜夏日", score: 7.2 },
    { title: "夏之终熄", score: 7.1 },
    { title: "星之终途", score: 6.9 },
    { title: "与鲨鱼共度的七日间", score: 7.5 },
  ],
  "2023": [
    { title: "初音岛5", score: 8.5 },
    { title: "樱之刻", score: 7.5 },
    { title: "甜蜜女友2+", score: 8.1 },
    { title: "天使☆嚣嚣 RE:BOOT!", score: 7.8 },
    { title: "纯白交响曲 SANA EDITION", score: 7.3 },
    { title: "我的眼睛能看光光！不可知的未来与透视的命运", score: 7.6 },
    { title: "神之国的魔法使", score: 7.7 },
    { title: "八卦恋爱", score: 7.5 },
    { title: "漂浮山丘", score: 6.4 },
    { title: "少女之剑与秘密协奏曲", score: 6.8 },
    { title: "恋爱少不了撒娇", score: 7.4 },
    { title: "GINKA", score: 7.8 },
  ],
  "2024": [
    { title: "我喜欢的人，喜欢女装的我", score: 8 },
    { title: "贽之匣庭", score: 7.6 },
    { title: "刹那绽放的恋之花火", score: 7.5 },
    { title: "启动世界的理想论", score: 7.3 },
    { title: "异想魅惑2 暮色廻奇谭", score: 7.8 },
    { title: "旭光的婚礼", score: 6.5 },
    { title: "丽露娅与夏夏的纯白谎言", score: 6.1 },
    { title: "天选庶民的真命之选", score: 7 },
    { title: "everlasting flowers", score: 6.8 },
    { title: "悠刻的命运少女", score: 6.7 },
    { title: "宝石少女 1st.cut:The Reason She Must Perish", score: 6.2 },
    { title: "播种之谣", score: 7.9 },
  ],
};

export default data;
